sudo: required
language: node_js
addons:
  hosts:
    - unpkg.com
node_js:
  - "0.11"
  - "0.12"
  - "4"
  - "5"  
  - "6"
  - "node"
  - "iojs"  
before_install: 
- npm install -g mocha
- sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
- ./scripts/setup-local-file-server.sh
